#!/bin/sh

if ! git diff-files --quiet _posts; then
	echo "posts are out of sync (skipping tag maintenance)"
	exit 0
fi

if ! (cd _posts; git diff-index --quiet origin/posts); then
	echo "posts are out of sync (skipping tag maintenance)"
	exit 0
fi

echo "cleaning tag feeds"
_oddbit/cleantagfeeds

echo "generating tag feeds"
_oddbit/gentagfeeds

git add -A tag
if ! git diff-index --quiet HEAD -- tag; then
	git commit -m 'automatic tag update' tag
fi

exit 0

