#!/bin/sh
#
# This script is meant to be used as a pre-push hook for git.  It ensures that
# the "posts" submodule is in a sane state before attempting to push the
# repository (to avoid generating tag feeds pointing at nonexistent posts).

if ! [ "$SKIP_PRE_PUSH_CHECKS" ]; then
	posts_branch=$(cd _posts && git rev-parse --abbrev-ref HEAD)
	if [ "$posts_branch" != "posts" ]; then
		echo "posts repo is on wrong branch (skipping tag maintenance)"
		exit 0
	fi

	if ! git diff-files --quiet _posts; then
		echo "posts are out of sync (skipping tag maintenance)"
		exit 0
	fi

	if ! (cd _posts; git diff-index --quiet origin/posts); then
		echo "posts are out of sync (skipping tag maintenance)"
		exit 0
	fi
fi

echo "cleaning tag feeds"
_oddbit/cleantagfeeds

echo "generating tag feeds"
_oddbit/gentagfeeds

git add -A tag
if ! git diff-index --quiet HEAD -- tag; then
	git commit -m 'automatic tag update' tag
fi

exit 0

