#!/bin/sh

if ! git diff-files --quiet _posts; then
	echo "posts are out of sync (skipping tag maintenance)"
	exit 0
fi

if ! (cd _posts; git diff-index --quiet origin/posts); then
	echo "posts are out of sync (skipping tag maintenance)"
	exit 0
fi

echo "cleaning tag feeds"
_oddbit/cleantagfeeds

# We expect errors from `find`, so put this
# after we clean things up.
set -e

echo "generating tag feeds"
_oddbit/gentagfeeds

if ! git diff-files --quiet tag; then
	echo 'committing tag feed updates'
	git add -A tag
	git commit -m 'automatic tag update' tag
fi

exit 0

