#!/bin/sh

postdir=_drafts

while getopts 'pdt:' ch; do
	case $ch in
		(p) postdir=_posts;;
		(d) postdir=_drafts;;
		(t) tags="${tags:+$tags }$OPTARG";
	esac
done
shift $(( $OPTIND - 1 ))

[ "$1" ] || exit

title=$1
slug=$(
	echo $title |
	tr -d '[[:punct:]]' |
	tr '[[:upper:]]' '[[:lower:]]' |
	tr '[[:space:]]' '-' |
	cut -c1-20
	)
slug=${slug%-}

[ "$slug" ] || {
	echo "ERROR: failed to generate slug." >&2
	exit 1
}

date=$(date +%Y-%m-%d)
post=$postdir/$date-$slug.md

cat > $post <<EOF
---
title: $title
date: $date
tags:
$(for tag in $tags; do
echo "  - $tag"
done)
---

Post starts here.
EOF

gvim $post

